---
title: "publications"
---

#### 2023

Anderson, B., Pannell, J., Billiard, S., Burgarella, C., de Boer, H., Dufay, M., __Helmstetter, A. J.__ ... & Glémin, S. (2023). Opposing effects of plant traits on diversification. *In press*, iScience. https://doi.org/10.1016/j.isci.2023.106362.

__Helmstetter, A. J.__, Zenil-Ferguson, R., Sauquet, H., Otto, S. P., Mendez, M., Vallejo-Marin, M., Schoenenberger, J., Burgarella, C., Anderson, B., de Boer, H., Glemin, S. & Kafer, J. (2022). Trait-dependent diversification in angiosperms: patterns, models and data. *In press*, Ecology Letters. 

Wood, D. P., Holmberg, J. A., Osborne, O. G., __Helmstetter, A. J.__, Dunning, L. T., Ellison, A. R., ... & Papadopulos, A. S. (2023). Genetic assimilation of ancestral plasticity during parallel adaptation to zinc contamination in Silene uniflora. Nature Ecology & Evolution, 1-10. https://doi.org/10.1038/s41559-022-01975-w

#### 2022

__Helmstetter, A. J.__, Glemin, S., Käfer, J., Zenil-Ferguson, R., Sauquet, H., de Boer, H., ... & Condamine, F. L. (2022). Pulled diversification rates, lineages-through-time plots, and modern macroevolutionary modeling. Systematic Biology, 71(3), 758-773. https://doi.org/10.1093/sysbio/syab083

Escobar, S., __Helmstetter, A. J.__, Montúfar, R., Couvreur, T. L., & Balslev, H. (2022). Phylogenomic relationships and historical biogeography in the South American vegetable ivory palms (Phytelepheae). Molecular Phylogenetics and Evolution, 166, 107314. https://doi.org/10.1016/j.ympev.2021.107314

#### 2021

__Helmstetter, A. J.__, Cable, S., Rakotonasolo, F., Rabarijaona, R., Rakotoarinivo, M., Eiserhardt, W. L., ... & Papadopulos, A. S. (2021). The demographic history of Madagascan micro-endemics: have rare species always been rare?. Proceedings of the Royal Society B, 288(1959), 20210957. https://doi.org/10.1098/rspb.2021.0957

Oztolan-Erol, N., __Helmstetter, A. J.__, İnan, A., Buggs, R. J., & Lucas, S. J. (2021). Unraveling genetic diversity amongst European hazelnut (Corylus avellana L.) varieties in Turkey. Frontiers in plant science, 12, 661274. https://doi.org/10.3389/fpls.2021.661274

Papadopulos, A. S., __Helmstetter, A. J.__, Osborne, O. G., Comeault, A. A., Wood, D. P., Straw, E. A., ... & Lighten, J. (2021). Rapid parallel adaptation to anthropogenic heavy metal pollution. Molecular biology and evolution, 38(9), 3724-3736. https://doi.org/10.1093/molbev/msab141

Escobar, S., __Helmstetter, A. J.__, Jarvie, S., Montúfar, R., Balslev, H., & Couvreur, T. L. (2021). Pleistocene climatic fluctuations promoted alternative evolutionary histories in Phytelephas aequatorialis, an endemic palm from western Ecuador. Journal of Biogeography, 48(5), 1023-1037.  https://doi.org/10.1111/jbi.14055

#### 2020

__Helmstetter, A. J.__, Béthune, K., Kamdem, N. G., Sonké, B., & Couvreur, T. L. (2020). Individualistic evolutionary responses of Central African rain forest plants to Pleistocene climatic fluctuations. Proceedings of the National Academy of Sciences. https://doi.org/10.1073/pnas.2001018117

Schley, R., Pennington, R., Pérez-Escobar, O., __Helmstetter, A. J.__, de la Estrella, M., Larridon, I., Kikuchi, I., Barraclough, T., Forest, F., & Klitgård, B. (2020). Introgression across evolutionary scales suggests reticulation contributes to Amazonian tree diversity. Molecular Ecology, 29(21), 4170-4185. https://doi.org/10.1111/mec.15616

__Helmstetter, A. J.__, Amoussou, B., Bethune, K., Kamdem, N., Kakai, R., Sonke, B., & Couvreur, T. L. P. (2020). Phylogenomic data reveal how climate shapes patterns of diversity in an African rain forest tree species. Molecular Ecology, 29(18), 3560-3573. https://doi.org/10.1111/mec.15572 **[recommended](10.24072/pci.evolbiol.100094) by PCI** 

Brée, B., __Helmstetter, A.J.__, Bethune, K., Ghogue, J.-P., Sonké, B., & Couvreur, T.L.P. (2020). Diversification of African Rainforest Restricted Clades: Piptostigmateae and Annickieae (Annonaceae). Diversity, 12, 227. https://doi.org/10.3390/d12060227 

__Helmstetter, A. J.__, Kamga, S., Bethune, K., Lautenschläger, T., Zizka, A., Bacon, C., Wieringa, J., Stauffer, F., Antonelli, A., Sonké, B., & others (2020). Unraveling the Phylogenomic Relationships of the Most Diverse African Palm Genus *Raphia* (Calamoideae, Arecaceae). Plants, 9(4), 549. https://doi.org/10.3390/plants9040549

__Helmstetter, A. J.__, Oztolan-Erol, N., Lucas, S., & Buggs, R. (2020). Genetic diversity and domestication of hazelnut (*Corylus avellana*) in Turkey. Plants, People, Planet, 2(4), 326-339 https://doi.org/10.1002/ppp3.10078

__Helmstetter, A. J__., Papadopulos, A., Igea, J., Van Dooren, T (2020). Trait evolution and historical biogeography shape assemblages of annual killifish. *In press*, Journal of Biogeography.  https://doi.org/10.1111/jbi.13912

#### 2019

Couvreur, T. L. P.\*, __Helmstetter, A. J.__\*, Koenen, E., Bethune, K., Brandao, R., Little, S., Sauquet, H., & Erkens, R. (2019). Phylogenomics of the major tropical plant family Annonaceae using targeted enrichment of nuclear genes. Frontiers in plant science, 9, 1941. https://doi.org/10.3389/fpls.2018.01941 \* __*joint first author*__

__Helmstetter, A. J.__, Buggs, R., & Lucas, S. (2019). Repeated long-distance dispersal and convergent evolution in hazel. Scientific reports, 9(1), 1–12. https://doi.org/10.1038/s41598-019-52403-2

__Helmstetter, A. J.__, & Van Dooren, T. (2019). Determinants of growth and body size in Austrolebias South-American annual killifish. bioRxiv. https://doi.org/10.1101/2019.12.31.891648

#### 2018

Parker, J., __Helmstetter, A. J.__, & Papadopulos, A. (2018). Rapid, raw-read reference and identification (R4IDs): A flexible platform for rapid generic species ID using long-read sequencing technology. bioRxiv, 281048. https://doi.org/10.1101/281048

Van Dooren, T., Thomassen, H., Smit, F., __Helmstetter, A. J.__, & Savolainen, V. (2018). Scope for sympatric giant-dwarf speciation driven by cannibalism in South-American annual killifish (Austrolebias). bioRxiv, 121806. https://doi.org/10.1101/121806

#### 2017

Parker, J., __Helmstetter, A. J.__, Devey, D., Wilkinson, T., & Papadopulos, A. (2017). Field-based species identification of closely-related plants using real-time nanopore sequencing. Scientific reports, 7(1), 1–8. https://doi.org/10.1038/s41598-017-08461-5

#### 2016

__Helmstetter, A. J.__, Papadopulos, A., Igea, J., Van Dooren, T., Leroi, A., & Savolainen, V. (2016). Viviparity stimulates diversification in an order of fish. Nature communications, 7, 11271. https://doi.org/10.1038/ncomms11271.
